configured_endpoints: 30
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/arcade-ai%2Farcade-engine-7ecb40b6650ff002eed02efd1b59c630abe1fb9eb70c9c916c15b115260e5003.yml
openapi_spec_hash: 2e5c04d1a50afcd0bdbd9737cec227c9
config_hash: b31a3f1bbe9abcc7bb144942d88ad1b6
